FROM node:20-alpine
ARG DEPLOY_ENV
ENV DEPLOY_ENV ${DEPLOY_ENV}
WORKDIR /app
COPY . .
WORKDIR /app/src
RUN npm install
# for prod
# RUN npm run build-prod
# for qa
# RUN npm run build-qa
# RUN npm run build
RUN npm run build-${DEPLOY_ENV}
RUN mkdir -p /app/server && mv /app/src/dist /app/server
WORKDIR /app/server
RUN npm install
EXPOSE 8080
CMD ["node", "server.js"]
