// ----------------------------------------------------
// SAMPLE DROPDOWNS (IDs start at 1)
// ----------------------------------------------------

import { DropdownOption } from '../models/DropDownOption';

export const pathways: DropdownOption[] = [
  { id: 1, name: 'IIT' },
  { id: 2, name: 'AIT' },
  { id: 3, name: 'HEOR' },
  { id: 4, name: 'Simulated clinical' },
];

export const rtiYears: DropdownOption[] = [
  { id: 1, name: '2025' },
  { id: 2, name: '2026' },
  { id: 3, name: '2027' },
  { id: 4, name: '2028' },
  { id: 5, name: '2029' },
];

export const productTypes: DropdownOption[] = [
  { id: 1, name: 'ATP_RND' },
  { id: 2, name: 'TIER_2_3_RND' },
  { id: 3, name: 'STRATEGIC_EXISTING' },
  { id: 4, name: 'OTHER_EXISTING' },
];

export const originRequests: DropdownOption[] = [
  { id: 1, name: 'Franchise' },
  { id: 2, name: 'Marketing' },
  { id: 3, name: 'Sales' },
  { id: 4, name: 'R&D Development' },
];

export const monadicComparative: DropdownOption[] = [
  { id: 1, name: 'Monadic' },
  { id: 2, name: 'Comparative' },
];

export const launchClaims: DropdownOption[] = [
  { id: 1, name: 'Yes' },
  { id: 2, name: 'No' },
];

export const statusOptions: DropdownOption[] = [
  { id: 1, name: 'DRAFT' },
  { id: 2, name: 'RESET' },
  { id: 3, name: 'NEED_INFO' },
  { id: 4, name: 'ABANDONED' },
  { id: 5, name: 'CREATED' },
  { id: 6, name: 'REVIEWED' },
  { id: 7, name: 'ASSESSED' },
  { id: 8, name: 'STUDY_ADDED' },
  { id: 9, name: 'PILOT_ADDED' },
  { id: 10, name: 'HARMONIZED' },
  { id: 11, name: 'DATA_CHECKED' },
  { id: 12, name: 'PRODUCT_RANKED' },
  { id: 13, name: 'TA_RANKED' },
  { id: 14, name: 'FUNDED' },
  { id: 15, name: 'NOT_FUNDED' },
];

// ----------------------------------------------------
// 1. SAMPLE DROPDOWN DATA (IDs normalized)
// ----------------------------------------------------

export const franchises: DropdownOption[] = [
  { id: 1, name: 'Contact Lens' },
  { id: 2, name: 'OTC' },
  { id: 3, name: 'Pharma' },
  { id: 4, name: 'Surgical' },
  { id: 5, name: 'NA' },
];

export const tas: DropdownOption[] = [
  { id: 1, name: 'VC - Contact lens', franchise_id: 1 },
  { id: 2, name: 'Refractive Suite', franchise_id: 4 },
  { id: 3, name: 'NA', franchise_id: 3 },
  { id: 4, name: 'Cataract Refractive Consumables', franchise_id: 4 },
  { id: 5, name: 'CRCX', franchise_id: 4 },
  { id: 6, name: 'Other', franchise_id: 4 },
  { id: 7, name: 'SX Glaucoma', franchise_id: 4 },
  { id: 8, name: 'Pharma - Glaucoma', franchise_id: 3 },
  { id: 10, name: 'Monofocal IOL', franchise_id: 4 },
  { id: 11, name: 'CRDX', franchise_id: 4 },
  { id: 12, name: 'PCIOL', franchise_id: 4 },
  { id: 13, name: 'Visualisation', franchise_id: 4 },
  { id: 14, name: 'Pharma - Dry Eye and Allergy', franchise_id: 3 },
  { id: 15, name: 'SX Retina', franchise_id: 4 },
  { id: 16, name: 'VC - Dry Eye', franchise_id: 2 },
];

export const brands: DropdownOption[] = [
  { id: 1, name: 'Travatan', ta_id: 8 },
  { id: 2, name: 'Precision 1 Sphere', ta_id: 1 },
  { id: 3, name: 'AIR OPTIX', ta_id: 1 },
  { id: 4, name: 'Eysuvis', ta_id: 14 },
  { id: 5, name: 'Infiniti', ta_id: 5 },
  { id: 6, name: 'Grieshaber', ta_id: 15 },
  { id: 7, name: 'Clacier', ta_id: 3 },
  { id: 8, name: 'AR-15512', ta_id: 14 },
  { id: 9, name: 'SF6', ta_id: 15 },
  { id: 10, name: 'Genteal', ta_id: 16 },
  { id: 11, name: 'Vigadexa', ta_id: 14 },
  { id: 12, name: 'Lacryvisc', ta_id: 16 },
  { id: 13, name: 'Opti-Free', ta_id: 1 },
  { id: 14, name: 'Voyager', ta_id: 7 },
  { id: 15, name: 'AutonoMe', ta_id: 10 },
  { id: 16, name: 'WaveLight EX500 Contoura / Topography Guided', ta_id: 2 },
  { id: 17, name: 'AcrySof', ta_id: 12 },
  { id: 18, name: 'LuxOR Revalia', ta_id: 5 },
  { id: 19, name: 'Kynex', ta_id: 16 },
  { id: 20, name: 'Monarch III', ta_id: 10 },
  { id: 21, name: 'WaveLight', ta_id: 2 },
  { id: 22, name: 'TOTAL30', ta_id: 1 },
  { id: 23, name: 'DAILIES', ta_id: 1 },
  { id: 24, name: 'Constellation', ta_id: 15 },
  { id: 25, name: 'Patanol S', ta_id: 14 },
  { id: 26, name: 'Naphtears', ta_id: 14 },
  { id: 27, name: 'WaveLight plus', ta_id: 2 },
  { id: 28, name: 'Verion', ta_id: 11 },
  { id: 29, name: 'Argos', ta_id: 11 },
  { id: 30, name: 'Simbrinza', ta_id: 8 },
  { id: 31, name: 'WaveLight InnovEyes', ta_id: 2 },
  { id: 32, name: 'Non-Product Specific', ta_id: 3 },
  { id: 33, name: 'Polyrinse', ta_id: 1 },
  { id: 34, name: 'Tobradex', ta_id: 14 },
  { id: 35, name: 'NA', ta_id: 15 },
  { id: 36, name: 'Custom-Pak, Cataract', ta_id: 4 },
  { id: 37, name: 'PRECISION7', ta_id: 1 },
  { id: 38, name: 'ORA', ta_id: 11 },
  { id: 39, name: 'Unity', ta_id: 5 },
  { id: 40, name: 'FreshLook', ta_id: 1 },
  { id: 41, name: 'HyperVit 30K', ta_id: 15 },
  { id: 42, name: 'ExPress', ta_id: 7 },
  { id: 43, name: 'Total 30 Sphere', ta_id: 1 },
  { id: 44, name: 'Clareon', ta_id: 10 },
  { id: 45, name: 'Tears Naturale', ta_id: 16 },
  { id: 46, name: 'C3F8', ta_id: 15 },
  { id: 47, name: 'CyPass', ta_id: 7 },
  { id: 48, name: 'Optilar', ta_id: 3 },
  { id: 49, name: 'PRECISION1', ta_id: 1 },
  { id: 50, name: 'Glaucoma', ta_id: 7 },
  { id: 51, name: 'Systane', ta_id: 16 },
  { id: 52, name: 'UltraVit 10K', ta_id: 15 },
  { id: 53, name: 'Pataday', ta_id: 14 },
  { id: 54, name: 'Dailies Total 1 for Astigmatism', ta_id: 1 },
  { id: 55, name: 'AOSept', ta_id: 1 },
  { id: 56, name: 'Naphcon A', ta_id: 14 },
  { id: 57, name: 'Monarch IV', ta_id: 10 },
  { id: 59, name: 'Precision 1 for Astigmatism', ta_id: 1 },
  { id: 60, name: 'Dailies Total 1 Multifocal', ta_id: 1 },
  { id: 61, name: 'Systane iLux', ta_id: 16 },
  { id: 62, name: 'Balance Tip', ta_id: 5 },
  { id: 63, name: 'Legion', ta_id: 5 },
  { id: 64, name: 'None', ta_id: 3 },
  { id: 65, name: 'Hydrus', ta_id: 7 },
  { id: 66, name: 'Azopt', ta_id: 8 },
  { id: 67, name: 'Nevanac', ta_id: 14 },
  { id: 68, name: 'Dailies Total 1 Sphere', ta_id: 1 },
  { id: 69, name: 'OVDs', ta_id: 5 },
  { id: 70, name: 'Clear Care', ta_id: 1 },
  { id: 71, name: 'Purepoint Laser', ta_id: 15 },
  { id: 72, name: 'Laureate', ta_id: 5 },
  { id: 73, name: 'Marlo', ta_id: 1 },
  { id: 74, name: 'TOTAL14', ta_id: 1 },
  { id: 75, name: 'Azarga', ta_id: 8 },
  { id: 76, name: 'BSS Plus', ta_id: 5 },
  { id: 77, name: 'Vitalux', ta_id: 3 },
  { id: 78, name: 'Custom-Pak, Vitreoretinal', ta_id: 15 },
  { id: 79, name: 'Diagnostics, Other', ta_id: 11 },
  { id: 80, name: 'AcrySof IQ', ta_id: 10 },
  { id: 81, name: 'AcrySert', ta_id: 10 },
  { id: 82, name: 'Revalia', ta_id: 5 },
  { id: 83, name: 'Vigamox', ta_id: 14 },
  { id: 84, name: 'AutoSert', ta_id: 10 },
  { id: 85, name: 'Ultravit 7.5K', ta_id: 15 },
  { id: 86, name: 'HyperVit 20K', ta_id: 15 },
  { id: 87, name: 'INTREPID Hybrid Tip', ta_id: 5 },
  { id: 88, name: 'Ultravit, Advanced 10K', ta_id: 15 },
  { id: 89, name: 'PanOptix', ta_id: 12 },
  { id: 90, name: 'EASYPACK FS200 PI', ta_id: 2 },
  { id: 91, name: 'Ngenuity', ta_id: 13 },
  { id: 92, name: 'Rhopressa', ta_id: 8 },
  { id: 94, name: 'BlephEx', ta_id: 16 },
  { id: 95, name: 'SMARTCataract', ta_id: 5 },
  { id: 96, name: 'Inveltys', ta_id: 14 },
  { id: 97, name: 'Centurion', ta_id: 5 },
  { id: 98, name: 'Other', ta_id: 6 },
  { id: 99, name: 'LenSx', ta_id: 5 },
  { id: 100, name: 'Rocklatan', ta_id: 8 },
];

export const products: DropdownOption[] = [
  { id: 1, name: 'Hydrus', brand_id: 90 },
  { id: 2, name: 'DAILIES TOTAL1 Multifocal', brand_id: 4 },
  { id: 3, name: 'Custom-Pak, Cataract', brand_id: 17 },
  { id: 4, name: 'ORA', brand_id: 46 },
  { id: 5, name: 'PanOptix Vivity', brand_id: 32 },
  { id: 6, name: 'Unity VCS', brand_id: 37 },
  { id: 7, name: 'FreshLook Illuminate', brand_id: 34 },
  { id: 8, name: 'Unity CS', brand_id: 49 },
  { id: 9, name: 'PRECISION1 Sphere', brand_id: 85 },
  { id: 10, name: 'AutonoMe', brand_id: 81 },
  { id: 11, name: 'Lacryvisc', brand_id: 21 },
  { id: 12, name: 'Wavelight Contoura', brand_id: 68 },
  { id: 13, name: 'Wavelight READ', brand_id: 37 },
  { id: 14, name: 'PRECISION1', brand_id: 51 },
  { id: 15, name: 'SF6', brand_id: 3 },
  { id: 16, name: 'AIR OPTIX Plus HydraGlyde Sphere', brand_id: 79 },
  { id: 17, name: 'Grieshaber Sharkskin', brand_id: 1 },
  { id: 18, name: 'Revalia', brand_id: 51 },
  { id: 19, name: 'Laureate', brand_id: 21 },
  { id: 20, name: 'LuxOR Revalia', brand_id: 21 },
  { id: 21, name: 'AutoSert', brand_id: 17 },
  { id: 22, name: 'Pataday', brand_id: 6 },
  { id: 23, name: 'Tobradex', brand_id: 40 },
  { id: 24, name: 'Systane', brand_id: 3 },
  { id: 25, name: 'AcrySof IQ UV only', brand_id: 87 },
  { id: 26, name: 'Centurion with Ozil', brand_id: 57 },
  { id: 27, name: 'Optilar', brand_id: 65 },
  { id: 28, name: 'OVDs', brand_id: 78 },
  { id: 29, name: 'DAILIES TOTAL1', brand_id: 48 },
  { id: 30, name: 'PanOptix Pro (POP 2.1 or POP 1.0)', brand_id: 51 },
  { id: 31, name: 'AIR OPTIX Aqua for Astigmatism', brand_id: 69 },
  { id: 32, name: 'Wavelight EX500 Wavefront Custom-Q', brand_id: 59 },
  { id: 33, name: 'Systane Balance', brand_id: 3 },
  { id: 34, name: 'Precision 1 for Astigmatism', brand_id: 51 },
  { id: 35, name: 'WaveLight Analyzer', brand_id: 54 },
  { id: 36, name: 'Systane Hydration', brand_id: 55 },
  { id: 37, name: 'Systane iLux 1.5', brand_id: 23 },
  { id: 38, name: 'SMARTCataract', brand_id: 3 },
  { id: 39, name: 'AcrySof IQ PanOptix', brand_id: 97 },
  { id: 40, name: 'Opti-Free', brand_id: 14 },
  { id: 41, name: 'PanOptix Pro', brand_id: 51 },
  { id: 42, name: 'Precision 1 Sphere', brand_id: 51 },
  { id: 43, name: 'Ngenuity 1.4', brand_id: 47 },
  { id: 44, name: 'Constellation', brand_id: 17 },
  { id: 45, name: 'FreshLook Colorblends', brand_id: 53 },
  { id: 46, name: 'Nevanac', brand_id: 27 },
  { id: 47, name: 'Systane Complete', brand_id: 3 },
  { id: 48, name: 'Grieshaber others', brand_id: 92 },
  { id: 49, name: 'Eagle DSLT', brand_id: 51 },
  { id: 50, name: 'Diagnostics, Other', brand_id: 56 },
  { id: 51, name: 'Ultrasert+', brand_id: 73 },
  { id: 52, name: 'AIR OPTIX Night & Day Aqua', brand_id: 39 },
  { id: 53, name: 'Systane Ultra', brand_id: 23 },
  { id: 54, name: 'Clareon', brand_id: 94 },
  { id: 55, name: 'AIR OPTIX Plus HydraGlyde for Astigmatism', brand_id: 82 },
  { id: 56, name: 'HyperVit 20K', brand_id: 21 },
  { id: 57, name: 'WaveLight EX500 Contoura / Topography Guided', brand_id: 51 },
  { id: 58, name: 'AIR OPTIX Aqua Multifocal', brand_id: 95 },
  { id: 59, name: 'Custom-Pak, Vitreoretinal', brand_id: 44 },
  { id: 60, name: 'PanOptix', brand_id: 6 },
  { id: 61, name: 'WaveLight Allegretto', brand_id: 22 },
  { id: 62, name: 'Dailies Total 1 for Astigmatism', brand_id: 10 },
  { id: 63, name: 'FreshLook Color Lenses', brand_id: 53 },
  { id: 64, name: 'AcrySert', brand_id: 36 },
  { id: 65, name: 'Patanol S', brand_id: 86 },
  { id: 66, name: 'TOTAL30 Sphere', brand_id: 40 },
  { id: 67, name: 'Systane iLux 2.0', brand_id: 23 },
  { id: 68, name: 'PRECISION7', brand_id: 88 },
  { id: 69, name: 'Clear Care', brand_id: 17 },
  { id: 70, name: 'Grieshaber Reflex Handle', brand_id: 100 },
  { id: 71, name: 'TOTAL30 for Astigmatism', brand_id: 40 },
  { id: 72, name: 'FreshLook One-Day', brand_id: 11 },
  { id: 73, name: 'Systane iCaps', brand_id: 23 },
  { id: 74, name: 'Non-Product Specific', brand_id: 14 },
  { id: 75, name: 'WaveLight Topolyzer', brand_id: 22 },
  { id: 76, name: 'AR-15512', brand_id: 51 },
  { id: 77, name: 'DAILIES All Day Comfort', brand_id: 44 },
  { id: 78, name: 'Clareon Vivity', brand_id: 17 },
  { id: 79, name: 'Travatan', brand_id: 40 },
  { id: 80, name: 'UNIPEXY', brand_id: 51 },
  { id: 81, name: 'DAILIES AquaComfort Plus Toric', brand_id: 89 },
  { id: 82, name: 'Balance Tip', brand_id: 17 },
  { id: 83, name: 'Wavelight EX500 waveligth plus', brand_id: 43 },
  { id: 84, name: 'Argos', brand_id: 28 },
  { id: 85, name: 'Systane Ultra PF', brand_id: 23 },
  { id: 86, name: 'Systane Geldrops', brand_id: 3 },
  { id: 87, name: 'BlephEx', brand_id: 17 },
  { id: 88, name: 'DAILIES TOTAL1 for Astigmatism', brand_id: 89 },
  { id: 89, name: 'Grieshaber Reflex Long', brand_id: 30 },
  { id: 90, name: 'TOTAL30', brand_id: 77 },
  { id: 91, name: 'ExPress', brand_id: 67 },
  { id: 92, name: 'Wavelight Streamlight', brand_id: 23 },
  { id: 93, name: 'Genteal', brand_id: 8 },
  { id: 94, name: 'AcrySof IQ monofocal', brand_id: 62 },
  { id: 95, name: 'Ultravit 7.5K', brand_id: 13 },
  { id: 96, name: 'Centurion', brand_id: 44 },
  { id: 97, name: 'Other', brand_id: 24 },
  { id: 98, name: 'Kynex', brand_id: 21 },
  { id: 99, name: 'Clareon monofocal', brand_id: 17 },
  { id: 100, name: 'Pataday once daily relief extra strength', brand_id: 6 },
  { id: 101, name: 'AcrySof IQ ReSTOR', brand_id: 97 },
  { id: 102, name: 'None', brand_id: 65 },
  { id: 103, name: 'AcrySof Multi-Piece', brand_id: 99 },
  { id: 104, name: 'Verion', brand_id: 37 },
  { id: 105, name: 'EASYPACK FS200 PI', brand_id: 26 },
  { id: 106, name: 'AcrySof IQ Toric UV only', brand_id: 5 },
  { id: 107, name: 'Wavelight EX500 Wavefront Optimized', brand_id: 2 },
  { id: 108, name: 'Systane iLux', brand_id: 51 },
  { id: 109, name: 'Eysuvis', brand_id: 53 },
  { id: 110, name: 'Ngenuity Data Fusion', brand_id: 50 },
  { id: 111, name: 'UNIFEYE', brand_id: 61 },
  { id: 112, name: 'Clacier', brand_id: 17 },
  { id: 113, name: 'AcrySof IQ PanOptix Toric', brand_id: 97 },
  { id: 114, name: 'Clareon PanOptix', brand_id: 80 },
  { id: 115, name: 'WaveLight plus EX500', brand_id: 74 },
  { id: 116, name: 'DAILIES Colors', brand_id: 89 },
  { id: 117, name: 'Wavelight', brand_id: 91 },
  { id: 118, name: 'TOTAL14', brand_id: 64 },
  { id: 119, name: 'DAILIES TOTAL1 Sphere', brand_id: 96 },
  { id: 120, name: 'Wavelight FS200', brand_id: 49 },
  { id: 121, name: 'Rocklatan', brand_id: 3 },
  { id: 122, name: 'Azarga', brand_id: 17 },
  { id: 123, name: 'Clareon Toric', brand_id: 17 },
  { id: 124, name: 'Vigadexa', brand_id: 37 },
  { id: 125, name: 'UltraVit 10K', brand_id: 51 },
  { id: 126, name: 'Precision7 Sphere', brand_id: 91 },
  { id: 127, name: 'Vigamox', brand_id: 22 },
  { id: 128, name: 'WaveLight Biograph', brand_id: 60 },
  { id: 129, name: 'LenSx', brand_id: 21 },
  { id: 130, name: 'Grieshaber Flex Loop', brand_id: 66 },
  { id: 131, name: 'Voyager', brand_id: 91 },
  { id: 132, name: 'AIR OPTIX', brand_id: 18 },
  { id: 133, name: 'Systane Original', brand_id: 23 },
  { id: 134, name: 'AIR OPTIX Aqua Sphere', brand_id: 39 },
  { id: 135, name: 'PRECISION7 Multifocal', brand_id: 35 },
  { id: 136, name: 'TOTAL30 Multifocal', brand_id: 40 },
  { id: 137, name: 'AcrySof IQ monofocal Toric', brand_id: 76 },
  { id: 138, name: 'AcrySof IQ ReSTOR Toric', brand_id: 97 },
  { id: 139, name: 'HyperVit 30K', brand_id: 91 },
  { id: 140, name: 'Monarch III', brand_id: 21 },
  { id: 141, name: 'Vitalux', brand_id: 22 },
  { id: 142, name: 'DAILIES AquaComfort Plus Multifocal', brand_id: 89 },
  { id: 143, name: 'Azopt', brand_id: 17 },
  { id: 144, name: 'Clareon PanOptix Toric', brand_id: 98 },
  { id: 145, name: 'FreshLook Dimensions', brand_id: 25 },
  { id: 146, name: 'Clareon Vivity Toric', brand_id: 17 },
  { id: 147, name: 'WaveLIght InnovEyes', brand_id: 51 },
  { id: 148, name: 'DAILIES AquaComfort Plus Sphere', brand_id: 44 },
  { id: 149, name: 'Marlo', brand_id: 21 },
  { id: 150, name: 'Hydrus Microstent', brand_id: 7 },
  { id: 151, name: 'Legion', brand_id: 21 },
  { id: 152, name: 'PRECISION7 for Astigmatism', brand_id: 52 },
  { id: 153, name: 'Systane Complete PF', brand_id: 3 },
  { id: 154, name: 'Infiniti', brand_id: 21 },
  { id: 155, name: 'C3F8', brand_id: 84 },
  { id: 156, name: 'Rhopressa', brand_id: 41 },
  { id: 157, name: 'BSS Plus', brand_id: 15 },
  { id: 158, name: 'Glaucoma', brand_id: 75 },
  { id: 159, name: 'Tears Naturale', brand_id: 40 },
  { id: 160, name: 'Ngenuity', brand_id: 21 },
  { id: 161, name: 'Systane Lid Wipes', brand_id: 23 },
  { id: 162, name: 'PRECISION1 for Astigmatism', brand_id: 9 },
  { id: 163, name: 'Pataday twice daily relief', brand_id: 6 },
  { id: 164, name: 'Simbrinza', brand_id: 3 },
  { id: 165, name: 'Inveltys', brand_id: 21 },
  { id: 166, name: 'Ultravit, Advanced 10K', brand_id: 33 },
  { id: 167, name: 'Pataday once daily relief', brand_id: 6 },
  { id: 168, name: 'AcrySof IQ Vivity', brand_id: 72 },
  { id: 169, name: 'Naphtears', brand_id: 31 },
  { id: 170, name: 'Naphcon A', brand_id: 16 },
  { id: 171, name: 'Systane PRO', brand_id: 45 },
  { id: 172, name: 'FreshLook One-Day Colors', brand_id: 83 },
  { id: 173, name: 'AcrySof IQ', brand_id: 74 },
  { id: 174, name: 'WaveLight plus', brand_id: 51 },
  { id: 175, name: 'Centurion with Active Sentry', brand_id: 20 },
  { id: 176, name: 'Dailies Total 1 Sphere', brand_id: 12 },
  { id: 177, name: 'CyPass', brand_id: 44 },
  { id: 178, name: 'Centurion Silver', brand_id: 44 },
  { id: 179, name: 'TOTAL30 Multifocal for Astigmatism', brand_id: 51 },
  { id: 180, name: 'TOTAL14 Sphere', brand_id: 51 },
  { id: 181, name: 'DAILIES All Day Comfort Toric', brand_id: 44 },
  { id: 182, name: 'Ultrasert', brand_id: 40 },
  { id: 183, name: 'Acrysof IQ Vivity Toric', brand_id: 63 },
  { id: 184, name: 'WaveLight Oculyzer', brand_id: 22 },
  { id: 185, name: 'Systane Hydration PF', brand_id: 70 },
  { id: 186, name: 'Unity Dx', brand_id: 49 },
  { id: 187, name: 'Purepoint Laser', brand_id: 35 },
  { id: 188, name: 'AOSept', brand_id: 38 },
  { id: 189, name: 'Ngenuity 1.5', brand_id: 42 },
  { id: 190, name: 'Systane Omega 3', brand_id: 23 },
  { id: 191, name: 'AIR OPTIX Plus HydraGlyde Multifocal', brand_id: 29 },
  { id: 192, name: 'INTREPID Hybrid Tip', brand_id: 21 },
  { id: 193, name: 'Monarch IV', brand_id: 21 },
  { id: 194, name: 'Dailies Total 1 Multifocal', brand_id: 19 },
  { id: 195, name: 'Total 30 Sphere', brand_id: 51 },
  { id: 196, name: 'FreshLook Colors', brand_id: 53 },
  { id: 197, name: 'AIR OPTIX Colors', brand_id: 39 },
  { id: 198, name: 'Systane Ointment', brand_id: 23 },
  { id: 199, name: 'Polyrinse', brand_id: 71 },
];

export const functions = [
  { id: 1, name: 'Marketing' },
  { id: 2, name: 'Franchise' },
  { id: 3, name: 'Cr&d' },
  { id: 4, name: 'Gma' },
  { id: 5, name: 'Heor' },
  { id: 6, name: 'R&d tech platform' },
  { id: 7, name: 'Global markets insights' },
];

export const roles = [
  { id: 1, name: 'Creator' },
  { id: 2, name: 'admin' },
  { id: 3, name: 'reviewer' },
  { id: 4, name: 'assessor' },
  { id: 5, name: 'harmonizer' },
  { id: 6, name: 'data_checker' },
  { id: 7, name: 'product_prioritizer' },
  { id: 8, name: 'ta_prioritizer' },
  { id: 9, name: 'funder' },
];
