import { Routes } from '@angular/router';
import { IdeaDashboard } from './features/ideas/idea-dashboard/idea-dashboard';
import { IdeaCreate } from './features/ideas/idea-create/idea-create';
import { MyIdeas } from './features/ideas/my-ideas/my-ideas';
import { ContactForHelp } from './features/contact-for-help/contact-for-help';
import { IdeaView } from './features/ideas/idea-view/idea-view';
import { IdeaEdit } from './features/ideas/idea-edit/idea-edit';
import { IdeaDraftEdit } from './features/ideas/idea-draft-edit/idea-draft-edit';
import { PrioritizationOne } from './features/prioritization-one/prioritization-one';
import { PrioritizationTwo } from './features/prioritization-two/prioritization-two';
import { Harmonizer } from './features/harmonizer/harmonizer';
import { AdminHome } from './features/admin/admin-home/admin-home';
import { ManageUser } from './features/admin/manage-user/manage-user';
import { AdminProduct } from './features/admin/admin-product/admin-product';

export const routes: Routes = [
  { path: '', component: IdeaDashboard },
  { path: 'addidea', component: IdeaCreate },
  { path: 'myideas', component: MyIdeas },
  { path: 'help', component: ContactForHelp },
  { path: 'ideas/:idea_uid', component: IdeaView },
  { path: 'ideas/:idea_uid/edit', component: IdeaEdit },
  { path: 'ideas/:idea_uid/edit-draft', component: IdeaDraftEdit },
  { path: 'productprioritization', component: PrioritizationOne },
  { path: 'taprioritization', component: PrioritizationTwo },
  { path: 'harmonizer', component: Harmonizer },
  { path: 'admin', component: AdminHome },
  { path: 'admin/users', component: ManageUser },
  { path: 'admin/products', component: AdminProduct },
];
